[project]
name = "basicmathlib"
version = "0.1.0"
description = "Librería de Matemática Básica para laboratorio de CI"
readme = "README.md"
requires-python = ">=3.10"

[tool.pytest.ini_options]
addopts = "-q"
testpaths = ["tests"]
pythonpath = ["src"]

